parameters:
  host: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.host }}
  pool: ${{ parameters.pool }}
  steps:
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: 'npm install -g @esy-nightly/esy@0.4.10-e6e1e7 --unsafe-perm'
      displayName: 'Installing deps'
  - ${{ if eq(parameters.sign, 'false') }}:
    - script: 'sudo npm install -g @esy-nightly/esy@0.4.10-e6e1e7 --unsafe-perm'
      displayName: 'Installing deps'
  - script: esy install
    displayName: 'Installing deps'
  - script: esy build
    displayName: 'Building'
  - ${{ if ne(parameters.sign, 'true') }}:
    - script: esy test
      displayName: 'Running inline tests'
  - script: esy npm-release
    displayName: 'Creating npm release'
  - script: npm pack
    displayName: 'NPM packing...'
    workingDirectory: '_release'
  - ${{ if eq(parameters.host, 'Windows') }}:
    - script: 'npm install -g .\pesy-0.0.0.tgz --unsafe-perm=true'
      displayName: 'npm link... for tests'
      workingDirectory: '_release'
  - ${{ if eq(parameters.host, 'Linux') }}:
    - script: 'sudo npm install -g ./pesy-0.0.0.tgz --unsafe-perm=true'
      displayName: 'npm link... for tests'
      workingDirectory: '_release'
  - ${{ if eq(parameters.host, 'macOS') }}:
    - script: 'sudo npm install -g ./pesy-0.0.0.tgz --unsafe-perm=false'
      displayName: 'npm link... for tests'
      workingDirectory: '_release'
  - ${{ if eq(parameters.sign, 'false') }}:
    - script: ./_build/install/default/bin/TestBootstrapper.exe
      displayName: 'Running tests'
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: .\_build\install\default\bin\TestBootstrapper.exe
      displayName: 'Running tests'
  - ${{ if eq(parameters.sign, 'false') }}:
    - script: ./_build/install/default/bin/TestPesyConfigure.exe
      displayName: 'Running tests'
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: .\_build\install\default\bin\TestPesyConfigure.exe
      displayName: 'Running tests'
